
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjywceehnmqxhpsffdps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqeXdjZWVobm1xeGhwc2ZmZHBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDUyMTIsImV4cCI6MjA2NTU4MTIxMn0.JUuuahSbnW2hYKfLxpKNrZ_l8zXhHBL1b-6lD4y7n7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
